[project]
name = "sumo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.21.6",
    "pandas>=1.1.5",
    "traci>=1.23.1",
]
